### ISSUE TITLE
Move intel from dedicated channel on discord to General channel

### ISSUE THREAD

**Issue by gbrann** [daniel-dsouza/eve-bot#3]
*FEATURE REQUEST* ability to move the intel from dedicated intel channel in Discord to the general channel instead. This will help all pilots be aware of TTL notices.

**Comment by daniel-dsouza** [comment]
hmm. If I do this, I'll move the channel name to system name mapping into the config file, although that would complicate matters. If a different person runs the bot, and has a slightly different config file, that could get very confusing.

No guarantees I'll put this in.

**Comment by daniel-dsouza** [comment]
i'll merge this once I get some of the parser fixes done.
